[package]
name = "cli-routeplanner"
version = "0.1.0"
edition = "2018"

[dependencies]
reqwest = { version = "0.10", features = ["json"] }
tokio = { version = "0.2", features = ["full"] }
geojson= "*"
