name: Rust

on:
  push: 

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check formatting
      run: rustup component add clippy && cargo clippy -- -D warnings
